apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name:  tuh
  namespace: argocd
spec:
  destination:
    namespace: dev
    server: https://kubernetes.default.svc
  project: default
  source:
    repoURL: https://github.com/s888n/srachdi_IOT.git
    path: manifests
    targetRevision: HEAD
  syncPolicy:
    automated:
      enabled: true
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true

